name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Application

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/project1
            docker pull origin main
            docker compose down
            docker compose up -d --build
